import cars01 from "./../components/fetured-items/img/item1.jpg"
import cars02 from "./../components/fetured-items/img/item2.png"
import cars03 from "./../components/fetured-items/img/item3.png"
import cars04 from "./../components/fetured-items/img/item4.png"
import cars05 from "./../components/fetured-items/img/item5.png"
import cars06 from "./../components/fetured-items/img/item6.png"

const data = [
	{
		id: 1,
		img: cars01,
		count: 1,
		color: "Red",
		size: "S",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 151.0,
		priceTotal: 151.0,
	},
	{
		id: 2,
		img: cars02,
		count: 1,
		color: "Red",
		size: "XS",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 152.0,
		priceTotal: 152.0,
	},
	{
		id: 3,
		img: cars03,
		count: 1,
		color: "Red",
		size: "XL",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 153.0,
		priceTotal: 153.0,
	},
	{
		id: 4,
		img: cars04,
		count: 1,
		color: "Red",
		size: "XL",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 154.0,
		priceTotal: 154.0,
	},
	{
		id: 5,
		img: cars05,
		count: 1,
		color: "Red",
		size: "XL",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 156.0,
		priceTotal: 156.0,
	},
	{
		id: 6,
		img: cars06,
		count: 1,
		color: "Red",
		size: "XS",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 157.0,
		priceTotal: 157.0,
	},

	{
		id: 7,
		img: cars01,
		count: 1,
		color: "Red",
		size: "M",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 158.0,
		priceTotal: 158.0,
	},
	{
		id: 8,
		img: cars02,
		count: 1,
		color: "Red",
		size: "M",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 159.0,
		priceTotal: 159.0,
	},
	{
		id: 9,
		img: cars03,
		count: 1,
		color: "Red",
		size: "L",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 160.0,
		priceTotal: 160.0,
	},
	{
		id: 10,
		img: cars04,
		count: 1,
		color: "Red",
		size: "XS",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 161.0,
		priceTotal: 161.0,
	},
	{
		id: 11,
		img: cars05,
		count: 1,
		color: "Red",
		size: "XL",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 162.0,
		priceTotal: 162.0,
	},
	{
		id: 12,
		img: cars06,
		count: 1,
		color: "Red",
		size: "S",
		title: "ELLERY X M'O CAPSULE",
		text: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
		price: 163.0,
		priceTotal: 163.0,
	},
];

export {data}